### ISSUE TITLE
min_history and state_to_update

### ISSUE THREAD

**Issue by zhouchunyi** [marctuscher/DRQN-tensorflow#2]
Hi, I want to use DRQN for my research, and I don't understand the parameters "min_history" and "state_to_update" in train. Could you give me a further explanation?

**Comment by marctuscher** [comment]
Sure.

In general, an LSTM needs sequences of datapoints to be trained successfully. However, for successful training of a Deep Q Network, datapoints need to be sampled mostly at random from the replay memory to keep the bias, a specific policy introduces low.  A tradeoff has to be made between successfully training an LSTM and not violating the DQN random sampling theorem too much.

"min_history" (e.g. 4):
For a datapoint from the replay memory to be used for training, its observation needs to have "min_history" number of preceding observations . These observations are then fed through the LSTM to generate a meaningful initial LSTM state.

"states_to_update" (e.g. 4 to 8):
After generating a meaningful LSTM state, the next "states_to_update" datapoints from the replay memory are used to train the DRQN.

For more information on this topic, have a look at:
https://arxiv.org/abs/1609.05521
